//! Approved Organization value-object vocabulary (TDS-0002).
//!
//! * `OrganizationId`
//! * `OrganizationName`
//! * `OrganizationStatus`
//! * `OrganizationType`
//! * `OrganizationVersion`
//!
//! All value objects are immutable, compare by value, have no independent
//! lifecycle, and have no repository. Construction and validation follow the
//! approved Milestone 1 domain decisions.

use crate::errors::{OrganizationError, OrganizationField};

/// Immutable, globally unique identity of the Organization aggregate
/// (TDS-0002; TDR-0006).
///
/// Generated by the aggregate through the injected `OrganizationIdGenerator`;
/// callers never supply it. Backed by a UUID v4.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OrganizationId(uuid::Uuid);

impl OrganizationId {
    /// Returns the canonical lowercase 36-character hyphenated textual form.
    ///
    /// The transport/persistence textual representation is governed by the
    /// TDR-0006 record.
    ///
    /// Returns an owned [`String`] because `uuid::Uuid` in the 1.x series
    /// does not expose a borrowed `&str` view of its hyphenated form.
    pub fn as_str(&self) -> String {
        self.0.to_string()
    }
}

impl From<uuid::Uuid> for OrganizationId {
    fn from(value: uuid::Uuid) -> Self {
        Self(value)
    }
}

impl core::fmt::Display for OrganizationId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        // `as_str` consumes `self`; clone the inner UUID to format without
        // moving out of a borrowed reference.
        f.write_str(&self.0.to_string())
    }
}

/// Required, immutable organization name.
///
/// Validated constructor: must contain at least one non-whitespace character.
/// The value is preserved exactly as supplied after boundary validation; no
/// normalization, case folding, length limit, or transformation is applied.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct OrganizationName(String);

impl OrganizationName {
    /// Constructs an `OrganizationName` from a non-whitespace value.
    ///
    /// # Errors
    ///
    /// Returns [`OrganizationError::Validation`] when the value is missing or
    /// contains no non-whitespace character.
    pub fn new(value: impl Into<String>) -> Result<Self, OrganizationError> {
        let value = value.into();
        if !contains_non_whitespace(&value) {
            return Err(OrganizationError::Validation(OrganizationField::Name));
        }
        Ok(Self(value))
    }

    /// Returns the stored name as str.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl core::fmt::Display for OrganizationName {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Immutable, string-backed organization type.
///
/// Per the approved OrganizationType Decision: the value is preserved exactly
/// as supplied, no enumeration, no normalization, and only missing or
/// whitespace-only values are rejected.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct OrganizationType(String);

impl OrganizationType {
    /// Constructs an `OrganizationType` from a non-whitespace value.
    ///
    /// # Errors
    ///
    /// Returns [`OrganizationError::Validation`] when the value is missing or
    /// contains no non-whitespace character.
    pub fn new(value: impl Into<String>) -> Result<Self, OrganizationError> {
        let value = value.into();
        if !contains_non_whitespace(&value) {
            return Err(OrganizationError::Validation(
                OrganizationField::OrganizationType,
            ));
        }
        Ok(Self(value))
    }

    /// Returns the stored type as str.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl core::fmt::Display for OrganizationType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Approved lifecycle status of the Organization aggregate.
///
/// Per MILESTONE-001-DOMAIN-DECISIONS, the initial externally observable
/// status of a created Organization is `Active`. The conceptual Created and
/// Initialized stages are transitioned within the creation operation and are
/// not externally observable. Further lifecycle states (Modified, Archived)
/// require separate authority and are intentionally not invented here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OrganizationStatus {
    /// The Organization is active and operational.
    Active,
}

/// Immutable version used for optimistic concurrency (TDS-0002).
///
/// The approved initial version of a created Organization is `1`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct OrganizationVersion(u64);

impl OrganizationVersion {
    /// The approved initial version of a newly created Organization.
    pub fn initial() -> Self {
        Self(1)
    }

    /// Constructs a version from a persisted `u64` value.
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Returns the underlying version number.
    pub fn value(&self) -> u64 {
        self.0
    }
}

impl core::fmt::Display for OrganizationVersion {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        self.0.fmt(f)
    }
}

/// Returns true when the string contains at least one non-whitespace character.
fn contains_non_whitespace(value: &str) -> bool {
    value.chars().any(|c| !c.is_whitespace())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn organization_id_renders_canonical_hyphenated_uuid() {
        let uuid = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        let id = OrganizationId::from(uuid);
        assert_eq!(id.as_str(), "550e8400-e29b-41d4-a716-446655440000");
    }

    #[test]
    fn organization_id_equality_is_by_value() {
        let uuid = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();
        assert_eq!(OrganizationId::from(uuid), OrganizationId::from(uuid));
    }

    #[test]
    fn organization_name_accepts_valid_value() {
        let name = OrganizationName::new("Forge").unwrap();
        assert_eq!(name.as_str(), "Forge");
    }

    #[test]
    fn organization_name_preserves_supplied_value() {
        let name = OrganizationName::new("  Spaced  ").unwrap();
        assert_eq!(name.as_str(), "  Spaced  ");
    }

    #[test]
    fn organization_name_rejects_empty() {
        let err = OrganizationName::new("").unwrap_err();
        assert_eq!(err, OrganizationError::Validation(OrganizationField::Name));
    }

    #[test]
    fn organization_name_rejects_whitespace_only() {
        let err = OrganizationName::new("   \t\n ").unwrap_err();
        assert_eq!(err, OrganizationError::Validation(OrganizationField::Name));
    }

    #[test]
    fn organization_name_equality_is_by_value() {
        let a = OrganizationName::new("Forge").unwrap();
        let b = OrganizationName::new("Forge").unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn organization_type_accepts_valid_value() {
        let t = OrganizationType::new("foundation").unwrap();
        assert_eq!(t.as_str(), "foundation");
    }

    #[test]
    fn organization_type_preserves_supplied_value() {
        let t = OrganizationType::new("  Custom Type  ").unwrap();
        assert_eq!(t.as_str(), "  Custom Type  ");
    }

    #[test]
    fn organization_type_rejects_empty() {
        let err = OrganizationType::new("").unwrap_err();
        assert_eq!(
            err,
            OrganizationError::Validation(OrganizationField::OrganizationType)
        );
    }

    #[test]
    fn organization_type_rejects_whitespace_only() {
        let err = OrganizationType::new("  ").unwrap_err();
        assert_eq!(
            err,
            OrganizationError::Validation(OrganizationField::OrganizationType)
        );
    }

    #[test]
    fn organization_type_equality_is_exact() {
        let a = OrganizationType::new("Forge").unwrap();
        let b = OrganizationType::new("forge").unwrap();
        assert_ne!(a, b);
    }

    #[test]
    fn organization_status_initial_observable_state_is_active() {
        let status = OrganizationStatus::Active;
        assert_eq!(status, OrganizationStatus::Active);
    }

    #[test]
    fn organization_version_initial_is_one() {
        assert_eq!(OrganizationVersion::initial().value(), 1);
    }

    #[test]
    fn organization_version_round_trips_persisted_value() {
        assert_eq!(OrganizationVersion::new(7).value(), 7);
    }
}