[package]
name = "forgeos-create-organization-application"
version = "0.1.0"
edition = "2024"

[dependencies]
forgeos-organization-domain = { path = "../../domains/organization-domain" }
thiserror = { version = "1", default-features = false }

[dev-dependencies]
uuid = { version = "1", features = ["v4"], default-features = false }
